name: package
on:
  push:
    tags:
      -'*'
  pull_request:
    branches: [ main ]
    tags:
      -'*'

env:
  DOTNET_VERSION: '6.0.405'
  WPF_PROJECT_PATH: WebBrowser.WPF/WebBrowser.WPF.csproj

jobs:
  build-and-package:
    # strategy:
    #   matrix:
    #     targetplatform: [ x86, x64 ]

    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Cores
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # - name: Decrypt PFX File
    #   run:  |
    #     echo "${{ secrets.ENCODED_PFX }}" > cert.pfx.asc
    #     certutil -decode cert.pfx.asc cert.pfx

    # - name: Add Cert to store
    #   run: certutil -user -q -p ${{ secrets.PFX_KEY }} -importpfx cert.pfx NoRoot

    - name: Install dependencies
      run: dotnet restore

    - name: Build     
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.WPF_PROJECT_PATH }} -c Release --self-contained -p:PublishSingleFile=true
      env:
        RuntimeIdentifier: win-x64

    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release: ${{ github.ref }}

    - name: Upload
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: WebBrowser.WPF/bin/Release/net6.0-windows/win-x64/publish/*.exe
        release-url: ${{ steps.create_release.outputs.upload_url }} 
