name: package
on:
  push:
    tags:
      -'*'
  pull_request:
    branches: [ main ]
    tags:
      -'*'

env:
  DOTNET_VERSION: '6.0.405'
  WPF_PROJECT_PATH: WebBrowser.WPF/WebBrowser.WPF.csproj

jobs:
  build-and-package:
    # strategy:
    #   matrix:
    #     targetplatform: [ x86, x64 ]
    permissions: write-all
    
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Cores
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # - name: Decrypt PFX File
    #   run:  |
    #     echo "${{ secrets.ENCODED_PFX }}" > cert.pfx.asc
    #     certutil -decode cert.pfx.asc cert.pfx

    # - name: Add Cert to store
    #   run: certutil -user -q -p ${{ secrets.PFX_KEY }} -importpfx cert.pfx NoRoot

    - name: Install dependencies
      run: dotnet restore

    - name: Build     
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.WPF_PROJECT_PATH }} -c Release --self-contained -p:PublishSingleFile=true
      env:
        RuntimeIdentifier: win-x64

    - name: Get previous tag
      id: previous_tag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next minor version
      id: minor_version
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      env:
        version: ${{ steps.previous_tag.outputs.tag }}
    
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.minor_version.outputs.patch }}
        release_name: Release ${{ steps.minor_version.outputs.patch }}

    - name: Upload
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: WebBrowser.WPF/bin/Release/net6.0-windows/win-x64/publish/*.exe
        release-url: ${{ steps.create_release.outputs.upload_url }} 
