name: build and test

on:
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.405'

jobs:
  build-and-test:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Cores
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal