name: Create Release

on:
  workflow_run:
    workflows: [ Avalonia Windows build and publish, WPF build and publish ]
    types: 
      - completed

jobs:    
  on-success:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: write
      
    steps:
      - name: Wait workflows
        uses: ahmadnassri/action-workflow-run-wait@v1
      
      - name: Download WPF artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: wpf-build-publish.yml
          
      - name: Download Avalonia windows artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: avalonia-win-build-publish.yml
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.0.${{ github.run_number }}
          prerelease : github.ref_name != 'main'
          makeLatest: github.ref_name == 'main'
          release_name: ${{ ( github.event_name == 'pull_request' && 'Pre-release' ) || 'Release' }} v0.0.${{ github.run_number }}
          artifacts: "**.exe"