name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      -  ['**.md', 'CrossBrowser.Avalonia/**', 'CrossBrowser.Native/**', 'CrossBrowser.WPF/**']
  pull_request:
    branches: [ main ]
    paths-ignore:
      -  ['**.md', 'CrossBrowser.Avalonia/**', 'CrossBrowser.Native/**', 'CrossBrowser.WPF/**']

env:
  DOTNET_VERSION: '6.0.405'
  TEST_RELEASE_CONFIGURATION: 'Test-Release'

jobs:
  run-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Test dependencies
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}

      - name: Build Test
        run: dotnet build --configuration ${{ env.TEST_RELEASE_CONFIGURATION}} --no-restore

      - name: Run Test
        run: dotnet test --configuration ${{ env.TEST_RELEASE_CONFIGURATION}} /p:CollectCoverage=true /p:Exclude="[*]Splat.*" /p:CoverletOutputFormat=opencover --no-restore --verbosity normal

      - name: Test Coverage
        uses: codecov/codecov-action@v3