name: Windows Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'CrossBrowser.Test/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'CrossBrowser.Test/**'

env:
  DOTNET_VERSION: '6.0.405'
  WPF_PROJECT_PATH: CrossBrowser.WPF/CrossBrowser.WPF.csproj

jobs:
  wpf-build-publish:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install WPF dependencies
        run: dotnet restore ${{ env.WPF_PROJECT_PATH}}

      - name: Build WPF
        run: dotnet build ${{ env.WPF_PROJECT_PATH}} -c Release --no-restore
      
      # TODO: sign package before publishing
      - name: Publish WPF
        run: dotnet publish ${{ env.WPF_PROJECT_PATH}} -c Release --self-contained -p:PublishSingleFile=true
        env:
          # TODO: support other RuntimeIdentifiers
          RuntimeIdentifier: win-x64
          
      - name: Install Avalonia Windows dependencies
        run: dotnet restore ${{ env.AVALONIA_PROJECT_PATH}} -p:Configuration=Avalonia-Win-Release

      - name: Build Avalonia Windows
        run: dotnet build ${{ env.AVALONIA_PROJECT_PATH}} -c Avalonia-Win-Release --no-restore
      
      # TODO: sign package before publishing
      - name: Publish Avalonia Windows
        run: dotnet publish ${{ env.AVALONIA_PROJECT_PATH}} -c Avalonia-Win-Release
        env:
          # TODO: support other RuntimeIdentifiers
          RuntimeIdentifier: win-x64

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.0.${{ github.run_number }}
          prerelease : github.ref_name != 'main'
          makeLatest: github.ref_name == 'main'
          release_name: ${{ ( github.event_name == 'pull_request' && 'Pre-release' ) || 'Release' }} v0.0.${{ github.run_number }}
          artifacts: "**.exe"