name: Windows Pre-release

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'CrossBrowser.Test/**'

env:
  DOTNET_VERSION: '6.0.x'
  WPF_PROJECT_PATH: CrossBrowser.WPF/CrossBrowser.WPF.csproj
  AVALONIA_PROJECT_PATH: CrossBrowser.Avalonia/CrossBrowser.Avalonia.csproj

jobs:
  windows-pre-release:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install WPF dependencies
        run: dotnet restore ${{ env.WPF_PROJECT_PATH}}

      - name: Build WPF
        run: dotnet build ${{ env.WPF_PROJECT_PATH}} -c Release --no-restore
      
      # TODO: sign package before publishing
      - name: Publish WPF
        run: dotnet publish ${{ env.WPF_PROJECT_PATH}} -c Release --self-contained -p:PublishSingleFile=true
        env:
          # TODO: support other RuntimeIdentifiers
          RuntimeIdentifier: win-x64
          
      - name: Install Avalonia Windows dependencies
        run: dotnet restore ${{ env.AVALONIA_PROJECT_PATH}} -p:Configuration=Avalonia-Win-Release

      - name: Build Avalonia Windows
        run: dotnet build ${{ env.AVALONIA_PROJECT_PATH}} -c Avalonia-Win-Release --no-restore
      
      # TODO: sign package before publishing
      - name: Publish Avalonia Windows
        run: dotnet publish ${{ env.AVALONIA_PROJECT_PATH}} -c Avalonia-Win-Release
        env:
          # TODO: support other RuntimeIdentifiers
          RuntimeIdentifier: win-x64
          
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semvers.outputs.v_patch }}
          prerelease : false
          makeLatest: true
          name: Pre-release ${{ steps.semvers.outputs.v_patch }}
          artifacts: "**/CrossBrowser.Avalonia.exe,**/CrossBrowser.WPF.exe"